## Red Wine Data Analytics Case Study

We are data analysts for a winery in California. Every year, the winery recieves a wine quality score from the Wine Critics Association (WCA) for each bottle of wine it produces. As this score drives wine sales, we are interested in maximizing this score to boost profits.

This year, you were brought along with the team and given a dataset of physicochemical properites and their respective scores. The winery wants you to run your statistical magic & figure out what properties should they focus on in order to get the highest score possible. Check out `data/winequality.README` to find out more about these columns.

This data model is located within the Amazon relational database (the very same database we are using for the capstone), so you must use `sqlalchemy` to extract your data. 

## Base Requirements

As always, ensure that you are completing all 3 steps of data analysis:

**Exploratory Data Analysis**
1. Univariate Relationships 
    * Visualize Distributions (via histograms & qq-plots)
    * Quantify Metrics (via kolmogorov-smirnov tests)
2. Bivariate Relationships
    * Scatter-Plots
    * Box-Plots
    * Heat Maps
3. Normalize Data

**Confirmatory/Diagnostic Data Analysis**
* Conduct hypothesis tests
* Conduct model training 

**Prescriptive Data Analysis**
* Recommend a course of action based on your findings.

This will be due on 5/17. Please be sure to answer all discussion questions for each respective section.

## Exploratory Data Analytics

1. 

2.

3.

In [1]:
import pandas as pd  
from sqlalchemy import create_engine
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

## Post Analysis

1. 

2.

3.

## Confirmatory Data Analytics

1. 

2.

3.

## Post Analysis

1. 

2.

3.

## Prescriptive Data Analytics

1. What